### ISSUE TITLE
Undeclared dependency App::Cmd::Tester (0.15_1)

### ISSUE THREAD

**Issue by eserte** [kjetilk/RDF-Generator-Void#8]
t/perlrdfapp.t fails if App::Cmd::Tester is not installed.

```
Can't locate App/Cmd/Tester.pm in @INC (you may need to install the App::Cmd::Tester module) ...
BEGIN failed--compilation aborted at t/perlrdfapp.t line 12.
t/perlrdfapp.t .. 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run
```

**Comment by kjetilk** [comment]
Yup, thanks, I'm aware and working to resolve it... The idea is I don't want a dependency there, it should skip those tests if App::Cmd::Tester isn't installed. I'll try putting the checks in a BEGIN block.

**Comment by kjetilk** [comment]
Great if you could rerun the test with the same setup on 0.15_2.

**Comment by kjetilk** [comment]
0.15_2 had a lot of passing tests, so releasing 0.16 now
